### ISSUE TITLE
information for old open files

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#104]
please add information if there are problems with the files.

![File](https://user-images.githubusercontent.com/13348933/129406915-14923bcd-7862-4f90-ac77-fa6d94267e71.jpg)

**Comment by Keidan** [comment]
Does this translation suit you?

- Отсутствие файла (удален или перемещен)
- Нет доступа к файлу, откройте его через меню

**Comment by OmlineEditor** [comment]
like that:
Файл отсутствует (удален или перемещен)
Нет доступа к файлу, откройте его через меню
