### ISSUE TITLE
[idea] can the input area be moved to another location?

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#105]
to improve data entry and make it easier to edit. you can reduce the input field to 8 characters as in the viewport and move this area to the place of the result.

everything is the same, only the text input will be in a different place. it's clearer and easier this way. what do you think as an idea?

![idea](https://user-images.githubusercontent.com/13348933/129418530-949e9d49-08c5-4e09-ad6a-1f3b6bcb94a0.jpg)

**Comment by Keidan** [comment]
I already thought about it, but it's too complicated to set up while preserving the coherence of the line alignment and the plain text...

**Comment by OmlineEditor** [comment]
I think no one will notice a skew of several pixels.

**Comment by Keidan** [comment]
If it was just a little lag... no, it's just horrible to deal with and it's worse with multiple text inserts. That's why I gave up on the idea.

**Comment by OmlineEditor** [comment]
OK, if there is an easy way to make this idea, I ask you to implement it.
