### ISSUE TITLE
save as...

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#107]
I open the file. I'm editing it. I save it under a different name through the ### **save as** menu. I enter letters, but they can only be accepted from the HEX range (numbers and letters from A to F).
I can't enter other letters and special characters.

**Comment by Keidan** [comment]
I don't understand.
Do you mean that when you want to enter the file name the application forces you to use hex characters?

**Comment by Keidan** [comment]
Forget my question I just reproduced it ^^'

**Comment by OmlineEditor** [comment]
> enter the file name the application forces you to use hex characters?

Yes, only  hex characters
