### ISSUE TITLE
reducing the file opening speed

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#111]
I check the speed of opening a file using large files.
at first, the opening speed is high. the file starts reading quickly at 1 MB per second, but then the speed drops to almost zero and I can't open a 20 MB file. depending on how many bits are in the line 8 or 16, the speed drops to zero approximately when opening a file with a size of 13 or 17 MB. when opening a file, the memory consumption reaches 370 MB. there is a lot of memory, there is still 900 MB free, but the file opens very slowly and it looks like the program has frozen.

to compare the opening of a large file, look at the program https://play.google.com/store/apps/details?id=com.myprog.hexedit
study the program, maybe you will take something useful function

**Comment by Keidan** [comment]
Why are you giving me the link to another application that is on the Google Store?
The applications are different... What do you think I can compare?

**Comment by OmlineEditor** [comment]
the applications are different, but they perform the same function. These are hexadecimal editors. compare your program with the one that I gave the link

**Comment by Keidan** [comment]
I just drastically modified the core of the application, though:
On Android each application being provided with upto 24/32mb of memory (which can go to as low as 16mb for older devices).

So I thought of increasing the limit via my Manifest file (largeHeap), so I can open much larger files but it causes many other problems (**solution rejected**)
I can add a native link for memory management (JNI), but I don't really want to spend a lot of time to implement this solution, and I'm not sure if it is supported by F-Droid (**solution rejected**).
I can implement a low memory detection, but according to the documentation it is not very reliable (**solution rejected**).
I can implement a sequential opening of the file, with a possibility to choose the start and end size (**solution selected**)

As I don't want to create a new specific menu (**non-negotiable**), I'll add a new step after the file selection to specify if the opening should be done in one shot or sequentially

**Comment by OmlineEditor** [comment]
using the link that I gave, another application opens large files and at the same time consumes 10 times less RAM.
how is this possible?
can you make it so that your program also consumes little memory and also opens large files quickly?

**Comment by Keidan** [comment]
The link is useless to me... And I don't want to spend more time on this subject!
I'm going to start from my original idea with a sequential file opening...

**Comment by Keidan** [comment]
Hi,

@OmlineEditor, @sr093906, I need your help :)

I would like to add the following texts and here are the translations I have:

| English  | Russian | Chinese | Description |
| ------------- | ------------- | ------------- | ------------- |
| Sequential opening  | Последовательное открытие  | 循序开放  | This text is on the same level as the "Open" menu. |
| In this mode it is not possible to add new data  | В этом режиме невозможно добавить новые данные  | 在这种模式下，不可能添加新的数据  | This text will be displayed if the user wants to add more data than allowed. |
| Start  | Начало  | 开始  | This text will be displayed for the beginning value of the file (bytes, megabytes, etc.). |
| End  | Конец  | 结束  | This text will be displayed for the end value of the file (bytes, megabytes, etc...). |

Does that sound right to you two?

**Comment by sr093906** [comment]
Sequential opening: 循序打开
In this mode it is not possible to add new data: 此模式下，不可能添加新的数据
Start: 初始值
End: 终值

**Comment by Keidan** [comment]
@sr093906 
I just changed the sentence:
"In this mode it is not possible to add new data"
to
"In this mode it is not possible to add or delete data"

Thank you very much

**Comment by sr093906** [comment]
Sequential opening: 循序打开
In this mode it is not possible to add or delete new data: 此模式下，不可能添加或删除新数据
Start: 初始值
End: 终值

**Comment by Keidan** [comment]
Thanks :blush:

**Comment by OmlineEditor** [comment]
Russian OK. all right. when the program is ready, it will be necessary to be ready, I need to think again about the logical meaning of the translation.

**Comment by Keidan** [comment]
I can make you screenshots

**Comment by OmlineEditor** [comment]
nothing is needed. make the program, if there are problems, we will fix them later. high accuracy of translation of the program, I think this is not a critical problem, translation is the main thing.
