### ISSUE TITLE
view in text

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#114]
I open a file where all the data is in one line, no line break lines.
switching the view in the text.
the program itself decides where to put the line break characters, this is about 70 characters per line.

with different font sizes, it turns out very ugly. or there are very few lines in a line or a couple of characters climb to another line.
![1](https://user-images.githubusercontent.com/13348933/130507773-2819e4c3-b873-40f1-8937-3b24276aae19.jpg)
![2](https://user-images.githubusercontent.com/13348933/130507777-f1b926b3-f951-46cc-ae37-668d75815561.jpg)
![3](https://user-images.githubusercontent.com/13348933/130507783-61b69f89-c191-4090-bc6d-ac5cf23e0e4f.jpg)

**Comment by Keidan** [comment]
In this view, I don't use line breaks but 70 bytes per line.
What you see is consistent with what I've coded.

**Comment by OmlineEditor** [comment]
it is a little inconvenient to look at if the font is large and there are 68 characters on one line and 2 characters on the second line.
is there any way to solve this?

**Comment by OmlineEditor** [comment]
you can first calculate how many characters are placed in a line for a given font, and then specify this number (for a place of 70).
