### ISSUE TITLE
the line numbers are incorrect

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#121]
- I open the file through the sequential opening menu
- I specify that to open from 100 bytes to the end
- after opening, I see that the lines are numbered from zero and not from 100 bytes (not from 0064 HEX)

it is necessary that the lines and addresses always match, regardless of how to open it.

**Comment by Keidan** [comment]
I can change/adjust the number of the starting line but I can't change the index of the column

**Comment by OmlineEditor** [comment]
you can add spaces at the beginning that don't mean anything. this will allow you to shift the text

**Comment by Keidan** [comment]
The application is not designed for that.... and I've to change a lot of things for that...

**Comment by OmlineEditor** [comment]
I think you will find a simple way to solve the problem
