### ISSUE TITLE
the idea is to replace the menu name

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#122]
now you have the name **_sequential opening_** in the menu. this is a little unclear for beginners and poorly reflects the meaning of the action.

a more understandable name is "open part of the file" or "open a piece of file" or "partial file opening".
I suggest you think about it and replace it with a more understandable name.

in Russian, a more logical name is "Открыть часть файла"

**Comment by Keidan** [comment]
Ok, thanks, I'll use "Partial file opening".

In Russian I should use "Открыть часть файла"?
@sr093906 do you have a translation to suggest for "Partial file opening"?

**Comment by OmlineEditor** [comment]
this is the most appropriate translation
"Partial file opening" = "Открыть часть файла"

**Comment by OmlineEditor** [comment]
add button
![button](https://user-images.githubusercontent.com/13348933/134820820-b517cc3d-de6e-4418-89cc-f20480f53e8f.jpg)

**Comment by sr093906** [comment]
"Partial file opening"：打开文件的一部分
