### ISSUE TITLE
reducing the file opening speed (again)

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#123]
the problem https://github.com/Keidan/HexViewer/issues/111 is not solved. large files in both modes (open and sequential open) cannot open.

**Comment by Keidan** [comment]
I can't do anything to solve this problem.
HexViewer can't open files of +20Mb

**Comment by OmlineEditor** [comment]
perhaps in the future there will be ideas and you will be able to solve the problem

**Comment by Keidan** [comment]
As I said in the issue you mentioned, Android limits to 20MB on new devices (less for old ones).
And the only known solutions to bypass the android limitations would be to use C/C++ to manage the memory or to implement partial openings (1) of the file that would be refreshed according to the user's actions (e.g. scrolling) and I don't have time to implement this kind of features.

(1) I already have the base but I would have to generalize the whole process and integrate it to the GUI actions but it's really long to code.

**Comment by OmlineEditor** [comment]
then add to the description or somewhere else information that it is impossible to open completely entire files over 20 MB. we need to somehow warn users that there are problems with opening large files
