### ISSUE TITLE
does not save

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#124]
- opening the file
- editing
- I click **_save as_**
- I specify a new file name
- I click OK to save
- I am told that the file was saved successfully
- I check and see that the file is there but its size is **_0 bytes_**

**Comment by Keidan** [comment]
I did a regression with my previous version (sorry)... but beware, from what I see with this bug, it's the source file that is overwritten :unamused:

**Comment by OmlineEditor** [comment]
if I click **_save as_** the source file should be unchanged, I save it under a different name. 
is the source file exactly changing?

**Comment by Keidan** [comment]
We didn't understand each other, I totally agree with you and it's not normal, that's why I corrected.
My warning was to inform you that this bug had altered your source file...
