### ISSUE TITLE
more details in the menu

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#125]
we need to make the menu more understandable and informative.

please take into account and open part of the file inclusive of the specified bytes. If it is specified from 8 to 10, then you need to open 3 bytes including the 8th, 9th and 10th bytes

![menu](https://user-images.githubusercontent.com/13348933/134820595-6175f3c4-a7d3-4a00-b6ab-4d8672142af0.jpg)

**Comment by Keidan** [comment]
@sr093906 Without wanting to abuse, could you please give me the translation of the following texts:
- Size file
- Size opening part
- Enter the beginning of the area to be opened and the end of the area to be opened.

**Comment by Keidan** [comment]
@OmlineEditor Can you also give me the translations please

**Comment by OmlineEditor** [comment]
Size file = Размер файла
Size opening part = Размер открываемой части

I think it will be shorter and more correct:
Enter the beginning and end of the area you want to open.  = Введите начало и конец области, которую нужно открыть.

**Comment by sr093906** [comment]
Size file: 文件大小
Size opening part: 要打开部分大小
Enter the beginning and end of the area you want to open: 输入要打开部分的初值和终值

Better to change 'size file' to 'file size' and 'size opening part' to 'size of the part to be opened'. Size can be used as a noun and a verb. Size sth means arrange or classify (things) in different groups according to size.
