### ISSUE TITLE
It is not possible to search for a word that is found on several lines.

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#129]
there is a file with the contents:
0123456789abcdef0123456789abcdef

in the program , the lines are split like this:
0123456789abcdef
0123456789abcdef

I want to find "f0", but these characters are on different lines and the program does not find them

**Comment by Keidan** [comment]
With what is coded .... Well, you can't... :disappointed:

**Comment by OmlineEditor** [comment]
it's not logical. you need to search without restrictions, without dividing into lines. we need to improve the search
