### ISSUE TITLE
problem of opening the file

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#137]
- click open part of the file
- switch to HEX mode
- specify the beginning of something with a hexadecimal letter, the end is just numbers
- return the mode to normal bytes and click open
- an error falls out

P.S. tell me, when did you completely make the application, are you testing it? I don't understand why there are so many errors that are very easy and quick to find

**Comment by Keidan** [comment]
I don't understand what you are talking about.
As there is no reconversion of values when switching from decimal to hexadecimal, yes if you have a letter (hex) when you switch back to decimal, there will be an error...

**Comment by OmlineEditor** [comment]
watch the video
https://user-images.githubusercontent.com/13348933/140808043-33c72071-1c90-4275-a116-1a45ee105b09.mp4

**Comment by Keidan** [comment]
Ok I understand
