### ISSUE TITLE
different font in byte and HEX mode

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#138]
the font is different and it is visible when switching mode.

![fonts](https://user-images.githubusercontent.com/13348933/140804984-61f11d2f-b80b-41a6-993b-ede6217ef468.gif)

**Comment by Keidan** [comment]
It's strange, I don't have this problem on my smartphone...

**Comment by OmlineEditor** [comment]
perhaps the problem is localization or something else related to different languages.

**Comment by Keidan** [comment]
This behavior is specific to android version < 11
