### ISSUE TITLE
ability to reduce the font size

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#14]
you can't put a small font in the default settings right now. now the minimum size is 12. for my smartphone with this font size it turns out very bad. if you change the font size to 6 or 9 then it turns out beautifully. please make the minimum size that the user can enter is 4
![1](https://user-images.githubusercontent.com/13348933/118376889-5bee4180-b5d3-11eb-8165-b7cc140ece70.jpg)
![2](https://user-images.githubusercontent.com/13348933/118376892-5d1f6e80-b5d3-11eb-9c63-1a50b3f2faf5.jpg)

**Comment by Keidan** [comment]
Hello,

Thank you for using this application :smiley:

I've made the following changes:
* It's now possible to use a font size smaller than 12 (sp).
* It's now possible to use a font size with a decimal number and not only an integer.
