### ISSUE TITLE
shows the wrong size

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#140]
the file size shows the wrong size if you enter the beginning of A, the end of ABC in HEX mode and then switch the mode back to decimal

![3](https://user-images.githubusercontent.com/13348933/140806199-d6d6fe08-4a76-4418-acc7-1bfd8663a867.jpg)

**Comment by Keidan** [comment]
-1 is displayed in case of conversion error

**Comment by OmlineEditor** [comment]
the converter needs to be fixed
