### ISSUE TITLE
incorrect insertion mode

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#141]
I open the file, click edit, enter the line in the mode of inserting real characters. if you insert the text at the beginning then there are problems, if at the end then there are no problems.

![4](https://user-images.githubusercontent.com/13348933/140807317-105a7b5e-6695-4dd0-afc2-f621412f520e.jpg)

**Comment by Keidan** [comment]
What string did you insert at the beginning of the line?

**Comment by OmlineEditor** [comment]
at first I just click on one character 0 (**_zero_**) on the keyboard

**Comment by Keidan** [comment]
And if the insertion mode is selected... with this manipulation, the application will crash...
