### ISSUE TITLE
Support for testspace

### ISSUE THREAD

**Issue by Keidan** [Keidan/HexViewer#142]

**Comment by Keidan** [comment]
@OmlineEditor As I don't necessarily test on all Android platforms but mainly on Android 11.
And to limit future problems, I added the support of "testspace".
Feel free to tell me if you want me to add/modify specific tests (they are available [here](https://github.com/Keidan/HexViewer/tree/master/specs/Manual%20Tests))

**Comment by OmlineEditor** [comment]
it's hard for me to say what needs to be added because I've never encountered this. There may be errors in very specific situations that are hard to program. if something is needed in the future, I will tell you, but for now we will leave it as it is.
