### ISSUE TITLE
complete file corruption

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#148]
- I open part of the file (from 95 to 98 bytes) for example, the file size is 98 bytes. opening the end of the file.
- edit and save the file (one byte at the end)
- I open the same file completely and see that the data in the interior of the file is gone, they are zeros except for the end of the file

![1](https://user-images.githubusercontent.com/13348933/143497881-773deeff-b8c3-4733-8f3b-b518ba66e290.jpg)

**Comment by OmlineEditor** [comment]
if you open a part of the file up to XX bytes, the file will be truncated at the end to XX bytes. so I have a 98 byte file that has become 5 bytes in size when opened from 0 to 5 bytes

**Comment by Keidan** [comment]
I tried both manipulations on Android 10 and on Android 11 but alas I don't reproduce your problem, I can edit the file partially at the beginning, in the middle and at the end and the size remains unchanged... The data in the file does not change except for the data that I changed manually.

**Comment by OmlineEditor** [comment]
maybe the problem is in another version of android, I have version 9.
reinstalling the application does not solve the problem. I can't figure out yet where the problem is.

**Comment by Keidan** [comment]
I just installed an Android 9 emulator and I reproduce the problem, I just have to understand why and fix it.
