### ISSUE TITLE
I can't open a large file

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#158]
when opened, the program freezes and shows this window for a very long period of time
the size is limited 312,5 * 1024 = 320 000 bytes
the way to open the full or part of the file does not matter, it is always buggy

did you do testing using the site, did you open large files there? why didn't you find this error using testspace the site?

P.S. I can't remember which website you use for this. add information to the main page that you are testing your program using XXXXX site

![1](https://user-images.githubusercontent.com/13348933/146395812-4400d3dc-5eb4-45c0-b5c8-d3fea4cc23d0.jpg)

**Comment by Keidan** [comment]
No I'd the tests with files smaller than 300kb... I'm really sorry for the inconvenience. You say "the way to open the full or part of the file doesn't matter, it is always buggy", do you mean that the feature really doesn't work or that you have the same problem?

**Comment by OmlineEditor** [comment]
regardless of the opening method, I can't open a full file over 312 KB or a part of a file if that part is over 312 kb

**Comment by OmlineEditor** [comment]
add large files for the test, preferably several 5, 10 and 15 MB
