### ISSUE TITLE
Partial opening and complete file

### ISSUE THREAD

**Issue by Keidan** [Keidan/HexViewer#166]
If a partial opening is requested but the complete file is opened, it should be considered as a normal opening.

@OmlineEditor What do you think about this feature?
Without this feature it is no longer possible to edit (add and/or remove) a file that is opened from an external file manager (as for #161)

**Comment by OmlineEditor** [comment]
such a hypothetical situation: now a person opens a file from 0 to 50 bytes (the file size is also 50 bytes, i.e. the full file is opened). a person changes the file size and the file becomes 65 bytes. what to do? in the history to store the opening of the full file or keep opening only the part from 0 to 50?
 in theory, you are right, and if you specify the entire file when opening a part of the file, then you need to store in the history the opening of not a part of the file, but the opening of the entire file completely.


I don't understand what it means won't work as in https://github.com/Keidan/HexViewer/issues/161 
give an example to make it clear

**Comment by Keidan** [comment]
In the case of an external opening (as in #161), only a partial opening is available, but if you do :
- Complete file opening (start=0, end=file size) (as in #161)
- With the current version, the edition is limited to a basic modification (no addition of lines, no deletion of lines)
- You do "Save as".
- With the current version, the file will be saved as a partially opened file and it will never be possible to make anything other than a basic modification.

**Comment by OmlineEditor** [comment]
but in problem #161 the file does not open with any of the three options:
- open the file completely - does not work
- opening part of the file from 0 to **file_size** - does not work
- opening only part of the file - does not work either

I can't do the opening in several stages because nothing works

**Comment by Keidan** [comment]
Yes, I know that :disappointed: I fixed it but you don't have the version.

**Comment by OmlineEditor** [comment]
if the problems have been fixed, I will look later

**Comment by Keidan** [comment]
I think I'll implement this and put an option in the configuration to enable or disable it.

For example, a checkbox that says (if you can translate it for me, that would be great):
"If a partial open is requested, but the entire file is opened, it is considered to be opened normally."

**Comment by Keidan** [comment]
I get the following translation:
Если запрашивается частичное открытие, но открывается весь файл, считается, что он открыт нормально.

Is this ok?

@sr093906  I get the following translation:
如果要求部分打开，但整个文件被打开，则被认为是正常打开。

Is this ok?

**Comment by sr093906** [comment]
如果要求部分打开，但打开了整个文件，则认为是正常打开。

**Comment by Keidan** [comment]
Thanks :)

**Comment by OmlineEditor** [comment]
maybe like this?

ENG: If a partial opening is requested, but the entire file is opened, then it is considered that it is fully opened as from the "open" menu.
RUS: Если запрашивается частичное открытие, но открывается весь файл, тогда считается, что он открыт полностью как из меню "открыть".

**Comment by Keidan** [comment]
thanks :)
