### ISSUE TITLE
blank screen when opening a modified file

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#168]
- I open a part of the file from 100 to 150 bytes. the file size is 200 bytes.
- edit and close
- another program changes the file size and it becomes less than 100 bytes, for example 90 bytes.
- I click the history and see what my file is in the list where it is indicated that I opened it from 100 to 150 bytes and I see that the file size has become 90 bytes.
- I click in the history to open part of the file as last time from 100 to 150 bytes.
- the file opens but the screen is empty

I ask you to add an alert and make it possible to re-specify the new size of the opened area because the file size has changed. and the file size is smaller than the area that should be open

**Comment by Keidan** [comment]
I will add the following message:
"The file size has changed, click to re-specify the new size"

I get the following translation:
Размер файла изменился, нажмите, чтобы повторно указать новый размер

Is this ok?

@sr093906 I get the following translation:
文件的大小已经改变，点击重新指定新的大小

Is this ok?

**Comment by sr093906** [comment]
ok

**Comment by Keidan** [comment]
thanks :)

**Comment by OmlineEditor** [comment]
maybe it's a little more clear to specify what is required from the user?

ENG: The file size has changed, click to specify the new size of the area to open
RUS: Размер файла изменился, нажмите, чтобы указать новый размер области для открытия


for the previous example, the translation is correct

**Comment by Keidan** [comment]
thanks :)
