### ISSUE TITLE
notification in partial file opening mode

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#169]
you can write when working with a part of the file at the bottom under the input text:
the size should be XX bytes, now ZZ bytes.
and the line should be red.

now only by clicking on the check mark you can find out that you cannot change the file size. it's a little unclear and inconvenient

**Comment by OmlineEditor** [comment]
you need to make a hint to make it easier to edit

![1](https://user-images.githubusercontent.com/13348933/146657677-3ba9ac6e-60e5-4a22-83ab-93695aaae9d4.jpg)

**Comment by Keidan** [comment]
I'm not going to add that just like that, but I'm going to do something.
