### ISSUE TITLE
improvement for text editing

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#17]
currently, only the edit option is used for editing using only specifying hexadecimal code. I don't remember all the codes for the characters. please add a table with symbols or create the ability to specify directly specify the text.

![1](https://user-images.githubusercontent.com/13348933/118986338-f067f380-b987-11eb-9814-fb385b596746.jpg)

**Comment by Keidan** [comment]
Hey,

Thanks for your feedback, I'll try to take this into account.


Note: I see that you are using a language that is not supported by the application, if you want, you can create the file app/src/main/res/values-bg/strings.xml (OTMEHA is Bulgarian isn't it?) with the translations and make a pull request so that I can officially add the support?

**Comment by OmlineEditor** [comment]
no, not Bulgarian, it's Russian. if there is an opportunity to make an adaptation and the possibility of supporting national languages, this is good.

**Comment by Keidan** [comment]
Okay, my bad, in this case the name of the directory changes:
it's not app/src/main/res/values-bg but (I put all available options for you to choose):
app/src/main/res/values-ru -> Russian (I think it's generic)
app/src/main/res/values-ru-rBY -> Russian in Belarus
app/src/main/res/values-ru-rKG -> Russian in Kazakhstan
app/src/main/res/values-ru-rKZ -> Russian in Kyrgyzstan
app/src/main/res/values-ru-rMD -> Russian in Moldava
app/src/main/res/values-ru-rRU -> Russian in Russia
app/src/main/res/values-ru-rUA -> Russian in Ukraine

**Comment by OmlineEditor** [comment]
the Russian language is the same everywhere, it does not differ in different countries.
Russian in Russia same as Russian in Belarus Russian in Belarus same as Russian in Ukraine same as ...

why do you want to divide the Russian language for several countries?

there are two languages in Ukraine: Russian and Ukrainian.
there are two languages in Belarus: Russian and Belarusian.
etc...

maybe it's better to send like this?
app/src/main/res/language/ru -> Russian (basic and the same for all countries of the former Soviet Union)
app/src/main/res/language/by -> Belarus
app/src/main/res/language/kz -> Kazakhstan
app/src/main/res/language/md -> Moldava
app/src/main/res/language/ua -> Russian in Ukraine

**Comment by Keidan** [comment]
Sorry I think I misspoke, in fact the directories I listed are those proposed by AndroidStudio.
app/src/main/res/language/ru would suit me fine

**Comment by OmlineEditor** [comment]
If there are two languages in the country where there is Russian, then it makes no sense to make a second language like Ukrainian and Belarusian. People from the former Soviet Union know Russian very well.

**Comment by Keidan** [comment]
It's now possible to edit a hexadecimal line directly by entering a plain text (the ASCII -> Hexadecimal mapping will be done automatically by the application).
CAUTION: With this new mode, there is no detection of key repetition (e.g. holding down the delete key).
