### ISSUE TITLE
in landscape orientation, the screen floor is wasted

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#171]
you can expand the number of columns in a row from 8 to 16 for landscape orientation. now the floor of the screen is not used and disappears

![1](https://user-images.githubusercontent.com/13348933/146684106-ad7dd721-f994-420e-8fa9-3be0fd4c106b.jpg)

**Comment by Keidan** [comment]
Sorry but I won't do dynamic 8/16 conversion (it takes too many parameters into consideration, especially the screen size and the number of pixels used to be able to display in 16 dynamically) and I don't want to make this part of the view customizable

**Comment by OmlineEditor** [comment]
well, then in landscape orientation, only half of the screen will be used. I can get used to it, but it's a little uncomfortable

**Comment by Keidan** [comment]
I understand and I'm sorry but it's really too boring to code and it's a source of more bugs and I think I have enough of them :(

**Comment by OmlineEditor** [comment]
well, then we leave it as it is and do not touch anything. close the ticket.
