### ISSUE TITLE
only the icon and the file name

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#172]
there is not enough space on the screen for the file name. now half of the screen is occupied by the name of the program. I suggest changing and doing the following:
- add an icon
- if there is nothing and it is not open, then there is an icon for the name of the program.
- if a file is open then there is only an icon and a file name
- remove the option to shorten the file name in the header from the menu. let's always show a maximum of characters without abbreviations. I think this is an extra option. why deprive yourself of useful information and shorten the file name?

what do you think about it?

![1](https://user-images.githubusercontent.com/13348933/146685346-860322cf-28f9-4ab5-ae2d-4827f17e4e41.jpg)

![2](https://user-images.githubusercontent.com/13348933/146685334-7b7f63b2-7dd4-4afc-86cf-e66cc6ce3e10.jpg)

![3](https://user-images.githubusercontent.com/13348933/146685335-57b2dca3-14bd-471f-8005-453c35e7a39f.jpg)

**Comment by Keidan** [comment]
I can remove the title of the application when a file is opened, but why don't you just increase the abbreviation?

**Comment by Keidan** [comment]
I just validated that Android seems to truncate the title itself, however I don't want to remove the search icon, that would be non-compliant with the Material Design recommendation.

**Comment by OmlineEditor** [comment]
we don't touch the search icon and it will remain. we increase the space under the file name, for this we remove the header if the file is open.
