### ISSUE TITLE
remove unnecessary editing features

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#176]
your program is almost perfect, everything works, there are no errors or I can't find them. but there is a strange behavior that is better to eliminate. the program tries to edit what it can't.

1) I add notes from another program to the calendar and they ask me how to edit a note? the list from my calendar and your program drops out, but your program cannot edit the calendar. you need to edit and remove the ability to edit calendar events

2) I connect a USB flash drive via OTG, they ask me how to watch files? through the file manager program or through yours. you also need to delete it because the program cannot open the whole disk.

3) I open a picture in a simple gallery https://f-droid.org/ru/packages/com.simplemobiletools.gallery.pro/ and try to edit it, but your program cannot open it. your program is not a photo editor. 

there seemed to be some other strange behavior, I don't remember what it was connected with, I didn't pay attention to it then. If I find the exact reason, I'll tell you.

**Comment by Keidan** [comment]
Thank you, you are a big part of it :)

I think the problem you are seeing is that the app registers for all mime types with Android.
If I reduce that and specialize the mime-type more, many files will not be able to be opened from the app anymore.
This weekend I'll see if I can specify the opening mime-type dynamically or not and "if" it's possible I'll make a change to put it in the settings.

**Comment by OmlineEditor** [comment]
if you have other projects and you want to find errors in them, you can try using this program PVS-Studio, it is free for open source https://pvs-studio.com/en/pvs-studio/.
have you heard or used this program?

**Comment by Keidan** [comment]
No, I didn't know, thanks for this discovery.
I have 2-3 open source compatible projects for which this type of analysis interests me, so I'll take a closer look :)

**Comment by Keidan** [comment]
Hello,

Bad news... I searched everywhere on the internet, but I don't really see a satisfactory solution to work around this problem.
In fact, to notify Android that the application is externally openable, I have to fill an xml tag in the AndroidManifest.xml file and this information is statically managed by Android... so I cannot do anything dynamically (runtime).
However, looking at my AndroidManifest.xml file, I realize that I'm using the android.intent.category.BROWSABLE tag which doesn't make sense for the application (because I don't manage it), so I'm going to remove it.

I don't really know if this change will fix or even limit what you see, but if not, I don't really have a solution...

**Comment by Keidan** [comment]
@OmlineEditor 
I come back to what you said:
> I open a picture in a simple gallery https://f-droid.org/ru/packages/com.simplemobiletools.gallery.pro/ and try to edit it, but your program cannot open it. your program is not a photo editor.

I installed the application on the emulator (I couldn't do it before) to see if I had a different behavior from my smartphone (on this one everything works and I always forget you're not on Android 11), and.... if I select an image from the application, then I go to edit and finally I select HexViewer, the file is not opened, the sizes are at 0, it's a bug \o/
I just corrected it and now the file is openable.

Regarding point 1, what application do you use so I can see what is going on and if it's normal?

Regarding point 2, I don't have a USB flash drive via OTG to test ... to see if the corrections I just made are sufficient.
