### ISSUE TITLE
[Translations] use weblate to manage translations

### ISSUE THREAD

**Issue by iNtEgraIR2021** [Keidan/HexViewer#180]
Hi @Keidan 

a while ago I translated HexViewer to German. I'm happy to see the number of translations growing since then.

To ease further translations and updates I suggest the use of weblate to manage the translations. Searching the closed issues I couldn't find any insights on this topic therefore I assume that nobody brought up this topic so far.

[**Weblate**](https://github.com/WeblateOrg/weblate) is an open source SaaS[^1] integrating as a git contributor into the dev workflow. Their[^2] public instance [hosted.weblate.org](https://hosted.weblate.org) is used by many big open source projects like F-Droid, Godot, NewPipe and Matomo.

Personally I use [weblate.bubu1.eu](https://weblate.bubu1.eu)[^3] to translate android apps from the german speaking F-Droid community. There's e.g. [currencies](https://github.com/sal0max/currencies) a currency converter app using different open APIs or [TinyWeatherForecastGermany](https://codeberg.org/Starfish/TinyWeatherForecastGermany) a weather app focused on Germany using open data provided by DWD.[^4]

Looking forward to your feeback on this.

Regards, Petra

[^1]: Software as a Service.
[^2]: the company uses the same name as its product.
[^3]: provided by  bubu (Marcus Hoffmann)
[^4]: Deutscher Wetterdienst -> Germany's national weather agency similar to NOAA in the US or météo france.

**Comment by Keidan** [comment]
Hello,

Thank you very much for your feedback, I will look into using weblate. :)

**Comment by iNtEgraIR2021** [comment]
@comradekingu might be able to help with the onboarding or forward you to somebody else of the team

**Comment by iNtEgraIR2021** [comment]
Full disclosure: I'm not affiliated with Weblate but a regular user of their services.

**Comment by Keidan** [comment]
Thank you very much, for the moment hosted.weblate.org, meets my needs.

I made a request for a free hosting, I'm waiting for the return and I'll take my final decision at this time.

The positive point is that thanks to weblate (and to you for this issue) I gained a new translation this morning :blush:

**Comment by comradekingu** [comment]
@Keidan
Got a nb_NO translation in.
I noticed the license says "GPLv3-only". GPLv3-or-later allows going to AGPLv3, or GPLv4 if that is good.
It can be changed in
https://hosted.weblate.org/settings/hexviewer/strings/
and
https://hosted.weblate.org/settings/hexviewer/glossary/

**Comment by Keidan** [comment]
I will change this, thank you very much
