### ISSUE TITLE
Add new languages for the interface

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#24]
Use this service to add new languages to the interface. It's free for open source projects.
https://crowdin.com/pricing

**Comment by Keidan** [comment]
Thanks but I prefer to let the community do the translations according to their needs.

**Comment by OmlineEditor** [comment]
that's right, people will do the translation themselves. this is just a site where it is convenient to do it. you do not need to make a translation, other users will do it.
