### ISSUE TITLE
Do you consider rewriting the page and changing it to a custom View

### ISSUE THREAD

**Issue by MartinKayJr** [Keidan/HexViewer#253]
operation is not convenient

**Comment by MartinKayJr** [comment]
It should learn from the 010 editor, the cursor can be operated freely in the view, support the built-in hexadecimal keyboard, input automatically moves the cursor, and the hexadecimal view is synchronized with the ascii view.

**Comment by MartinKayJr** [comment]
The display of rows should be clearly defined, and it supports plug-in recognition of the template results of different files

**Comment by Keidan** [comment]
Hello,

Which page are you talking about?

**Comment by MartinKayJr** [comment]
Hex Main Page

**Comment by Keidan** [comment]
When I created the application, I chose not to allow free input in the main view, and I'm afraid that now, to allow such a thing, I'd have to modify a large part of the application's structure (bearing in mind that we're not on a PC).

However, I'm not closed to PR, so if you want to suggest changes, you're free to do so.
