### ISSUE TITLE
Problem when trying to open file 

### ISSUE THREAD

**Issue by marcossmtp** [Keidan/HexViewer#256]
In my Xiaomi Redmi 9C with android 11 when I use open file and I select a file nothing happened, it returns to the main screen.
When I see logcat not error happned, and if I use the inverse method, use a file  explorer select a file and with "open with" I select the app it open the file correctly.
This problem not happened in my Samsung A33.

**Comment by Keidan** [comment]
Hello,

Thank you for your issue.

Not having a "Xiaomi Redmi 9C" (or even a Xiaomi at all), I'll see if I reproduce the problem with emulators, if not, the only thing I can do is implement a log system to try to see what's going on.

**Comment by Keidan** [comment]
Hello,

I've just made version 1.43, which includes the logs system (at the bottom of the settings page), so it'll be available on F-Droid in a few days.

Feel free to come back to me then and give me the logs of the Xiaomi Redmi 9C, so I can see if I have enough logs to understand what's going on.
