### ISSUE TITLE
Batch deletion of rows

### ISSUE THREAD

**Issue by Keidan** [Keidan/HexViewer#26]
Added the possibility to delete several lines at the same time

**Comment by Keidan** [comment]
Hello @sr093906 ,

I have modified the following fields:
| Field  | English | Chinese |
| ------ | ------- | ------- |
| items_selected | %1$d Selected | %1$d 选定 |
| items_deleted  | %1$d lines were deleted | %1$d 行被删除 |

I thank you in advance, if you could take a few minutes to tell me if the translation suits you :blush:

--------
Hello @sguinetti,

I have modified the following fields:
| Field  | English | Spanish |
| ------ | ------- | ------- |
| action_recently_open_title | Recently opened | Abierta reciente |
| error_file_not_found | The file %1$s was not found | No se ha encontrado el archivo %1$s |
| error_file_permission | No permission has been granted for file %1$s | No se ha concedido permiso para el archivo %1$s |


I thank you in advance, if you could take a few minutes to tell me if the translation suits you :blush:

**Comment by sr093906** [comment]
https://github.com/Keidan/HexViewer/pull/27/files

**Comment by Keidan** [comment]
@sr093906 tyvm :)
