### ISSUE TITLE
license_ GPL-3.0-only or GNU GPL v3 or later

### ISSUE THREAD

**Issue by jindam-vani** [Keidan/HexViewer#260]
@Keidan 
* https://gitlab.com/fdroid/fdroiddata/-/blame/master/metadata/fr.ralala.hexviewer.yml#L4 list as ```GPL-3.0-only```
* https://github.com/Keidan/HexViewer/#license lists as ```GNU GPL v3 or later```
* which is correct?

**Comment by Keidan** [comment]
Hello,

"GPLv3-or-later" seems the most correct.
I changed this a while ago and didn't know there was this information in "F-Droid", otherwise I would've made a change request.

**Comment by Keidan** [comment]
Thank you very much :)
