### ISSUE TITLE
"save" and "save as" in menu

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#28]
Right now, there is only an option in the "save" menu, but this option only works as "save as". the menu opens, the file is selected, and if there is a file, it asks if it needs to be overwritten?

please make two options "save" and "save as" in menu.
"save - save the file under the same name and overwrite it without question
"save as" - the current position of the work. open a menu with a selection of files ask for the file name, and if the file exists ask if it needs to be overwritten.

two options in the menu this is the standard menu for all editors.

**Comment by Keidan** [comment]
It is now possible to save the opened file directly (a Save As option has also been added). 

**Attention:** It's necessary to refresh the permissions of the recent files, for that reopen the files directly via the menu "Open" or simply by deleting the data of this application.
