### ISSUE TITLE
Copy option?

### ISSUE THREAD

**Issue by misha-franz** [Keidan/HexViewer#284]
Nice, simple, useful app. Many thanks. Could you please add a copy option (ability to select a line, in both hex and plain modes and then copy into the clipboard).

**Comment by Keidan** [comment]
Hello,

Thanks :)

**Hex:** 
Do you want only the hexadecimal part or the whole line :
_Hex only :_
31 31 31 31 31 31 31 31
_Whole line:_
31 31 31 31 31 31 31 31 11111111

**Plain:** 
Do you want what is displayed or the raw line (today, characters that are not displayed are replaced by '.')?

**Comment by misha-franz** [comment]
Hi,

Thanks for your quick reply.  It is up to you.  So far I only used the app to open configuration files with .cfg extension - not many apps can do that, your does.  The files I open are plain text without special characters.

Thanks,
Michael

**Comment by Keidan** [comment]
Hello,

The option will be available in the next version.
