### ISSUE TITLE
idea make it easier/faster to view both hex and plain text (ASCII) at the same time

### ISSUE THREAD

**Issue by clach04** [Keidan/HexViewer#291]
**Is your feature request related to a problem? Please describe.**

Tedious UX for enabling/disabling viewing both hex and text.

**Describe the solution you'd like**

Support hex and plain text (7-bit) us-ascii at the same time, similar to xxd (part of vim) andoither hex viewers

**Describe alternatives you've considered**

Can't think of any, seeing both is a common UI/UX for hex readers/editors.

**Additional context**

Check out screenshots of

  * https://play.google.com/store/apps/details?id=com.progwhiz.hexedit
  * https://www.google.com/search?q=xxd&client=firefox-b-1-m&sca_esv=591690802&tbm=isch&sxsrf=AM9HkKmtD6ClulxMfeoWE9r6wsTjZ_D1Cg:1702834019442&source=lnms&sa=X&ved=0ahUKEwi7htyG_5aDAxV_HEQIHcP8CwQQ_AUIBygC&biw=414&bih=722

Thanks for making this! I had an super small file, 660 bytes, that I couldn't view without this app. I was getting ready to send it to my PC when. I found you app on FDroid

**Comment by clach04** [comment]
Hmmm https://github.com/Keidan/HexViewer/blob/master/fastlane/metadata/android/en-US/images/phoneScreenshots/4.jpg indictates this support is already present.

**Comment by clach04** [comment]
Current support requires opening setting, portrait, height/font/size, display of data column.

The menu (without settings) already has a view plain/text, potentially could add a new item to the menu.

**Comment by Keidan** [comment]
Thank you for your message.

You can activate the feature by putting your smartphone/tablet in landscape mode.

You can activate it in portrait mode (Settings -> Portrait -> "Display of data column").
As screens are small in portrait mode, I chose to disable it by default).

**Comment by Keidan** [comment]
Regarding the change request.
I'm sorry, but I don't think it's appropriate to add a new option for this.

Since all it takes is a screen rotation (I agree, you've to know that...), I think that's the quickest option.

**Comment by clach04** [comment]
You gave me a workaround/solution, no apologies necessary :-)

Final idea/suggestion, new menu item with a help option. Could be a link to a (new) wiki, with some hints and tips, like the screen rotation.

Again, many thanks for making this app available. I've hardly used it yet but it was already very useful to me 🙏

**Comment by clach04** [comment]
Recommend adding a wont-fix label to this.
