### ISSUE TITLE
Majidgerami4651@gmail.com

### ISSUE THREAD

**Issue by Bitcoi2020** [Keidan/HexViewer#307]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Android version: [e.g. 12]
 - Version [e.g. 1.50]

**Log**
Application log (Settings -> Logs).

**Comment by Keidan** [comment]
???

**Comment by Keidan** [comment]
As I've no information or details on this issue, I'll close it.
