### ISSUE TITLE
Crushing when trying to open file as hex from apps for example opening picture as hex with hex viewer from x-plore file manager

### ISSUE THREAD

**Issue by User1l0** [Keidan/HexViewer#39]

**Comment by Keidan** [comment]
Hello,

I installed x-plore file manager and I don't reproduce the crash with version v1.13 & Android 11.

What version of Android are you using?
What version of the HexViewer are you using?

Can you wait for the release of version 1.13 and redo the test with this version? Indeed on version 1.13 I modified the code to avoid crashes when opening files and also things related to the file permission system of Android.

**Comment by User1l0** [comment]
There's no apk so Im using the latest version 1.12 from fdroid on android 10

**Comment by OmlineEditor** [comment]
> There's no apk so Im using the latest version 1.12 from fdroid on android 10

wait 1-2 days. new version coming soon on f-droid

**Comment by Keidan** [comment]
Exactly,
however, regarding your problem, you might have other problems... see the fixes that will be in [v1.14](https://github.com/Keidan/HexViewer/milestone/7).

In the last few weeks I've improved the application a lot, but I'm ashamed to admit that I've completely neglected what I originally developed the application for... which is your use case.
