### ISSUE TITLE
save option does not work

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#44]
I open the document, edit it, I press the save button, the message appears: "Uri exception" document is not saved.
if you choose the option to "save as..." and select the file name then everything works and saves the document.

I still don't understand the error message "Uri exception", can you replace it with a more logical and informative one to understand what the problem is?

**Comment by Keidan** [comment]
I think you are in the case treated in the answer here #28 .

Can you confirm that you are in this case, if so, there is nothing I can do, before issue #28, it was missing a specific request for permmission that can not be obtained without going through open, maybe the couple "open + save as" is necessary.

**Comment by OmlineEditor** [comment]
only the "save" menu does not work in the new version 1,13.
file I open the file via the open menu.
I remember what you wrote. I deleted the application cache but it didn't help.

save - not work
save as... - work OK 

Android 9.0
Redmi Note 7

[log.zip](https://github.com/Keidan/HexViewer/files/6711644/log.zip)

**Comment by OmlineEditor** [comment]
for the test, I uninstalled the application completely and re-installed it. the result is the same.
save - not work
save as... - work OK

**Comment by Keidan** [comment]
Ok thanks, I will install an Android 9 emulator to test.
