### ISSUE TITLE
problem when inserting unicode characters, part of the data from the clipboard is lost

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#51]
in the clipboard I have unicode characters, I want to open the file and change the emoticons in it to my own. I'm trying to paste text from the clipboard, but only part of the complete code is pasted.

✌ - these are three characters: e2 9c 8c 
♥ - these are three characters:  e2 99 a5
but always only inserted: e2
part of the data from the clipboard is lost.

**Comment by Keidan** [comment]
The tests I did are conclusive but to be seen in use.

The initial problem came from the fact that I was using the number of characters in input whereas the number of characters in input is different from their representation in bytes.

Then to have "e2 9c 8c" it's necessary to take into account that on android an emoji is coded in UTF-16, example U+1F604 is represented in UTF-16 as U+D83D U+DE04.

**Comment by OmlineEditor** [comment]
it seems to me that the text is copied to the clipboard in UTF-8. it is clearly not UTF-16
https://unicode-table.com/en/2665/
![uft8](https://user-images.githubusercontent.com/13348933/124152607-5c1ba100-da9c-11eb-8c88-98238befb774.PNG)

**Comment by Keidan** [comment]
Yes, the emoji itself is normalized to UTF-8, but android returns a code with a surrogate pair
