### ISSUE TITLE
Hexadecimal search in plain text mode does not work if there are spaces

### ISSUE THREAD

**Issue by Keidan** [Keidan/HexViewer#57]
If I search for example "3e 3c", the search does not work, but if I search for "3e3c", it works.

**Comment by OmlineEditor** [comment]
check to see if it works if there are 2 or 3 spaces. Or if the space is replaced with a tab

**Comment by Keidan** [comment]
You mean if the user enters (for example) "3e 3c", "3e (spaces) 3c" or even "3e (a tab) 3c".
Or just if the user is looking for a space or a tab?

**Comment by OmlineEditor** [comment]
the user can enter text, and the user also pastes text from the clipboard. anything can be in the clipboard copied from the site. there can be multiple spaces, not one space. there may be tabs. or maybe a combination of them where there are spaces and tabs together.

**Comment by Keidan** [comment]
I doubt you can paste multiple sentences (component limitation) but technically I'll search if what is in the search box is contained in a line.

However, if there are the following lines:
"azerty0123"
"456789"

and the user searches for 2345, I won't find the occurrence because I can't join all the lines together  (for performance reasons) and not try to guess if the word is on multiple lines to match correctly.

**Comment by OmlineEditor** [comment]
I'll see the new version when it comes out on f-droid, I'll think about how best to do it. I think in a couple of releases you will have a better file editing program. did you think to put it on the play.google.com site?

**Comment by Keidan** [comment]
I prefer to stay on the confidential side that f-droid represents.
And I'm not a fan of the comments section on the Google store (too many hater)
