### ISSUE TITLE
German Translation of strings.xml

### ISSUE THREAD

**Issue by iNtEgraIR2021** [Keidan/HexViewer#61]
Hi 👋🏼 

I love this great app and thought I'd might of help to add a translation of [strings.xml](https://github.com/Keidan/HexViewer/blob/master/app/src/main/res/values/strings.xml) to German.

I'll add the file below

Greetings, Petra

**Comment by iNtEgraIR2021** [comment]
[strings__de.txt](https://github.com/Keidan/HexViewer/files/6758349/strings__de.txt)

**Comment by Keidan** [comment]
Hello,

Thanks :blush:

The translation will be available in version [v1.15](https://github.com/Keidan/HexViewer/milestone/8).
