### ISSUE TITLE
highlighting lines does not work

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#64]
- I open the file
- I highlight one line
- I press the button to select all lines
- I press on the lines to remove some lines from the selection
- an inscription appears that there are 1 fewer lines in the selection
- but the lines with the selection are not missing, all the lines are still selected
- click on the lines to remove a few more lines from the selection
- an inscription appears that there are 1 fewer lines in the selection
- but the lines with the selection are not missing, all the lines are still selected

**Comment by Keidan** [comment]
Thank you very much for your valuable feedback which helps me a lot.

I don't understand exactly what the problem is. Is it possible to provide me with a screenshot of what you are getting?

**Comment by OmlineEditor** [comment]
Here is the problem when the lines are not removed if they are selected. it seems to me that you select them twice and the program does not take into account the visibility

https://user-images.githubusercontent.com/13348933/124924683-5ece4700-e004-11eb-9987-e1a84aa3136c.mp4

**Comment by Keidan** [comment]
Thanks to the modifications made for the issue #69 , I was able to reproduce this problem :tada:.
