### ISSUE TITLE
add line numbers

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#68]
when editing, if you need to select a specific address offset, you need to know the address.
there are no line numbers now.
I ask you to make it possible to display the addresses of the strings.
to improve, you can select the address in the menu, but you will need to remove one column of data so that everything fits on a small screen

**Comment by Keidan** [comment]
It's now possible to display line numbers (in portrait mode, the data part is not displayed if the total width of the line is more than 75% of the screen).

e.g:
![Screenshot_2021-07-10-22-31-13-15_46379e9dd1f994e02edf2a433a489205](https://user-images.githubusercontent.com/3134348/125175786-b7514000-e1ce-11eb-89ee-d3d6a165081a.jpg)
![Screenshot_2021-07-10-22-31-04-89_46379e9dd1f994e02edf2a433a489205](https://user-images.githubusercontent.com/3134348/125175789-bddfb780-e1ce-11eb-92c1-e64552beb02a.jpg)

The title at the top is static, so it will keep the same position after a scroll.

**Comment by OmlineEditor** [comment]
you have strange line numbers. I think they shouldn't be like that. in other programs they look different
![screen3](https://user-images.githubusercontent.com/13348933/125176218-6cd5c080-e1da-11eb-8c35-e653f3e7ea5c.jpg)
![screen2](https://user-images.githubusercontent.com/13348933/125176219-6fd0b100-e1da-11eb-984a-863e02109263.PNG)
![screen1](https://user-images.githubusercontent.com/13348933/125176220-6fd0b100-e1da-11eb-9b68-544792e602ef.PNG)

**Comment by Keidan** [comment]
Yes, I forgot to add the offset :yum:
