### ISSUE TITLE
this question is not a problem

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#69]
now the minimum android version for the application is 7.0. Is this really the minimum required version or is it you who set the restrictions? is it possible to change the minimum version in the code at least to android 6.0? I have friends who cannot update their devices and they are quite old and they have an android 6.0 version, they cannot use your program. Can you downgrade to android 6.0 to reach more users?

**Comment by Keidan** [comment]
No, no, this is just a totally arbitrary decision.
So I can lower the minimum supported version, but since there's a big gap in the file system management between Android M and the newer versions (including SD card support), I'll have to change a lot of things to make it fully compatible.

**Comment by OmlineEditor** [comment]
ok if it's hard close the request

**Comment by Keidan** [comment]
Yes, I'll close this issue soon (as soon as I finish testing) because I just added support for android M.
