### ISSUE TITLE
mode "overwrite only"

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#71]
there are files in which changing the size is undesirable. you only need to change the content and **not** add new characters. if you add at least 1 character, everything can break. please add to the editing mode the ability to only change and overwrite the content without the ability to add new characters. now such work takes place through the deleted added a new character, it is a little not convenient and does not look like the work of a HEX editor on a computer .

**Comment by Keidan** [comment]
You want an option that locks the size of the editing area?
For example, prohibit validation if there is one character less or more?

**Comment by OmlineEditor** [comment]
no. analog of the insert mode (only overwriting) in **_Notepad++_** if the "insert" button is pressed. I enter characters and they are overwritten, nothing is deleted, nothing is added. or the standard mode of operation of the HEX editor called **_HxD_**

https://github.com/notepad-plus-plus/notepad-plus-plus/  - Notepad++
https://mh-nexus.de/en/ - HxD

**Comment by Keidan** [comment]
Yes, but you talk about PC applications, and this application is not a PC application...

I can propose a lock as mentioned above but for the rest...
* The plain text editing mode makes it very difficult for me.
* I don't really know how to put this into practice knowing that we are not on a PC application and therefore the user experience is totally different.

**Comment by OmlineEditor** [comment]
implementation of the idea:
example
1) If you enter 1 character **_A_** in HEX mode, delete 1 character and enter 1 character. (this is 1 character of 2 characters: 31 => **_A_** 1 if the cursor is on the first character or 31 => 3 **_A_** if the cursor is on the 2nd character)
2) if the text mode when entering a character, delete 2 characters or more, depending on how much data is needed for a character (for UTF-8 there may be 2 ... 4 characters)  enter 1 character **_k_**   on screen:  31 => 6b
3) if inserted from the clipboard, delete it by the length of the clipboard and replace it with new text

I think this is exactly how it is implemented. I'm sure you can implement, you are a good programmer

**Comment by Keidan** [comment]
In your idea, this option simply overwrites the next character and does not limit the number of characters to be validated?

So:
* If the user deletes a character, the behavior remains unchanged.
* If the user adds a character and there is nothing after, the behavior remains unchanged.

Is this correct?

**Comment by OmlineEditor** [comment]
I think it's true, but it's hard for me to understand. English is not my language, it's hard to understand complex logic. but if there are problems, they can be fixed.

**Comment by Keidan** [comment]
No problem.

On Monday I'll start testing on the different versions of Android (M, P, R) and then I'll do the release.
And then if the modification is not satisfactory you'll create a new issue :smirk:
