### ISSUE TITLE
save button is not active

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#74]
- start the file manager (I use the total commander, it doesn't matter, you can use another one)
- set up a file manager to open an arbitrary file in your program
- open a new file that we have not opened before
- editing the file
- open the menu in order to save
- **_save_** option is not active. only the _**save as**_ button is active. 
- to solve the problem, you need to overwrite the file through the **_save as_** menu, only then the **_save_** button will be active

in other programs there is no such problem. I think the problem is that you are using the built-in system to access files. Is it possible to make the program itself get access to files and get standard permissions to access files on the phone?

**Comment by Keidan** [comment]
Yes this is normal, as I state in the README.MD :

...
Opening all files without a corresponding Android application (1).
...
(1) At first, the file can only be saved via "save as" and due to Android permissions reasons, the only way to make it appear in the list of recent files is to reopen it.
...

**Comment by OmlineEditor** [comment]
This not normal. it is not logical, it is not convenient. I analyzed what the problem is. other programs have permission to write any files on the system. you do not have this permission so crutches are used.

android.permission.READ_EXTERNAL_STORAGE - you have it
android.permission.WRITE_EXTERNAL_STORAGE - you do not have this permission, you need to add it for convenience.

**Comment by Keidan** [comment]
https://developer.android.com/about/versions/11/privacy/storage

**Comment by Keidan** [comment]
I have coded the application with the new constraints in mind. So I can't rely on WRITE_EXTERNAL_STORAGE permissions and this constraint is not really a constraint, just use "save as".

**Comment by OmlineEditor** [comment]
try adding WRITE_EXTERNAL_STORAGE and test it work. I think this problem can be solved somehow. if these restrictions cannot be circumvented, then in the new version all file managers and all programs that work with files will break. This is very bad news if the problem cannot be resolved in version 11.

**Comment by Keidan** [comment]
On Android 11 it does not work, I already tested it and that's why I switched to this mode.

And I don't want user experiences to differ between Android versions, so everyone will go through the "save as" menu when opening the file from an external application.

**Comment by OmlineEditor** [comment]
this is inconvenient, but if it is impossible otherwise then we will suffer :(

**Comment by OmlineEditor** [comment]
if there is no write permission you can simulate as if the user clicked save as to get permission

**Comment by Keidan** [comment]
Developers are the first to suffer from this... This constraint makes applications more complex... and believe me, I'd rather do without this kind of constraint.

No, unfortunately I can't get the permissions without going through a system Intent (ACTION_OPEN_DOCUMENT_TREE & ACTION_OPEN_DOCUMENT) which necessarily opens a file browser...

**Comment by OmlineEditor** [comment]
for the test, you can pass the opening of the file in the program Acode https://f-droid.org/ru/packages/com.foxdebug.acode/

do the same as in your application, open and try to change the text and **_save_** without **_save as_**.
if it does not work there then open a ticket in this application and see if the developer will do it and find a solution to the problem. if a solution already exists then you need to study this application.


I don’t have andriod 11, and I don’t have any of my friends, I can’t test it.

**Comment by Keidan** [comment]
It's not really the browser that will give the permissions.
To make it simple, it's at the time of the call of the intent (ACTION_OPEN_DOCUMENT_TREE or ACTION_OPEN_DOCUMENT) that android will grant the permissions for the requesting application.

**Comment by OmlineEditor** [comment]
if we cannot solve the problem then close this ticket and we will come back to it later
