### ISSUE TITLE
A little wish ...

### ISSUE THREAD

**Issue by ulrichloose** [Keidan/HexViewer#81]
In order to be able to enjoy the landscape format, you have to enable the automatic in the system - but that bothers me with many other applications.

Couldn't you implement a vertical / horizontal button in the Hexviewer so that you can manually switch to landscape format?

**Comment by Keidan** [comment]
This option will be available in version [V1.17](https://github.com/Keidan/HexViewer/milestone/10).

**Comment by ulrichloose** [comment]
I am thrilled ... Thank you very much!
