### ISSUE TITLE
Load file too slow

### ISSUE THREAD

**Issue by akavscode** [Keidan/HexViewer#84]
It load file too slow, 156.25Kb per sec??

**Comment by OmlineEditor** [comment]
Is it possible to open the file not completely, but only the part that needs to be shown on the screen? as we rewind and move the file, we will read the file in parts

**Comment by Keidan** [comment]
Sorry, but, although the idea is interesting, I can't add this kind of functionality... if the edited part is changed in size, it will be hell to rebuild the file, and honestly, I don't particularly want to engage in this kind of development...

**Comment by OmlineEditor** [comment]
so that the file does not change in size, you made the overwrite function (analogous to the insert button on the keyboard).
can you make a high-speed mode only if the file does not change in size? open and edit only the part of the file that is on the screen.

**Comment by Keidan** [comment]
I fixed the problem, and now opening a 1.61 MB file (for example) takes ~2 seconds.

@OmlineEditor Can you make another issue please, it will be easier and I will see if I implement it or not.
I need to think about the feasibility, but I will do so after analyzing all of your issues that make me think of a Christmas list  :smirk:.

**Comment by OmlineEditor** [comment]
ok, do it as you see fit
