### ISSUE TITLE
one or two columns on the screen

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#85]
now there are always 2 columns on the screen, 16 characters per line. this is irrational for phones because the screen is 2 times different vertically and horizontally. is it possible to add to the settings a choice of how many characters there will be in the line 8 (1 column) or 16 (2 columns)?
for vertical and horizontal positions, you can change the number of characters per line.
if you do, then you can edit it more conveniently. and you can make a large font if people have poor eyesight and they do not see small letters.

**Comment by Keidan** [comment]
I am sorry but I think I will not implement this proposal.
My decision is motivated by the following reasons:
- In mode 8, the list is twice as big and therefore twice as many context variables, thus a much higher consumption of memory resources.
- A change from mode 8 to mode 16 makes it impossible to use the undo/redo functions because the line indexes will no longer be identical.
- A change from mode 8 to mode 16 imposes a recalculation of the lines and on large files this is the same as reloading the file completely (except that I have to preserve the changes).

**Comment by OmlineEditor** [comment]
always store 8 characters in memory. only when there are 16 characters per line, you seem to have 2 times 8 characters each.
this is an easy way to get around the restriction.
What do you think?

**Comment by Keidan** [comment]
No sorry that doesn't change anything I mentioned above

**Comment by OmlineEditor** [comment]
if you specify only 8 or only 16 characters for portrait and landscape mode at the same time. is it possible?

**Comment by Keidan** [comment]
The 8 bothers me, it really consumes a lot of resources

**Comment by OmlineEditor** [comment]
we will display a message in the settings that if you want 8 characters in place 16 then it will consume more resources.

**Comment by Keidan** [comment]
To finalize this feature, I need your help

**Parameter name :** _Number of bytes to display per line._
**Parameter description:** _Number of bytes to display per line (8 or 16). Please note that the display of 8 bytes increases the memory requirement considerably._

**Error if the parameter is changed while a file is open:** _It's not possible to change the mode when a file is open._

Here is the translation with DeepL:
**Parameter name :** _Количество байтов для отображения в одной строке_
**Parameter description:** _Количество байтов для отображения в одной строке (8 или 16). Обратите внимание, что отображение 8 байт значительно увеличивает потребность в памяти._
**Error if the parameter is changed while a file is open:** _Невозможно изменить режим, когда файл открыт._

Does this sound right to you?

**Comment by OmlineEditor** [comment]
almost true.
It's a little better there:

**Parameter name**: Количество байт для отображения в одной строке
**Parameter description**: Количество байт для отображения в одной строке (8 или 16). Обратите внимание, что отображение 8 байт значительно увеличивает потребление памяти.
**Error if the parameter is changed while a file is open**: Невозможно изменить режим, когда файл открыт.

**Comment by OmlineEditor** [comment]
if you edit small files, I think the memory consumption will be unnoticeable, just a little more. no one will edit files of 100 megabytes or more.
