### ISSUE TITLE
more convenient and intuitive editing mode

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#88]
make the editing mode more understandable.
the original view is as in the view mode.
the editing mode is also as similar as possible to the viewing mode and is more understandable and convenient.
there are line numbers there are position codes, more convenient.
some of the functionality is not necessary, you can enter plain text in another field.
in the future, you can edit multiple lines and more than one line.

as an option, you can add arrows to move by position if people do not have arrows on the keyboard. this will make editing easier.

![new](https://user-images.githubusercontent.com/13348933/127542242-e38f649a-94ee-48c3-986f-0e19eae49f74.png)

**Comment by Keidan** [comment]
The design is interesting but what bothers me here is that I don't really see the criteria for adding a new line or deleting an existing line...
Anyway, I will try to make something more intuitive than the version currently available in the application.


I don't guarantee the support of the arrows

**Comment by OmlineEditor** [comment]
I don't understand what you mean when you say add or remove lines?

> I don't guarantee the support of the arrows

I have arrows, I don't care. I am worried about other users who do not have arrows on the standard keyboard.

**Comment by Keidan** [comment]
I know this isn't exactly what you want, but for now, I can propose this:
![IMG_20210731_195823](https://user-images.githubusercontent.com/3134348/127748646-0da92d33-a227-4812-9ed1-dc53d661f3d8.jpg)

**Comment by OmlineEditor** [comment]
yes, that's more convenient. 
but hiding options for text and insertion in the menu is a little awkward. can make them on the screen?
it's simpler and clearer.

**Comment by Keidan** [comment]
Ok, why not, but if I do that, I have to lock the orientation of this view in portrait mode, because with this design, I don't have enough space to display everything in landscape mode.

**Comment by OmlineEditor** [comment]
in landscape mode, you can scroll. You don't need to place everything on the screen, just scroll.
