### ISSUE TITLE
insertion mode error

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#91]
- I'm starting to edit
- I turn on the insert only mode
- I put the cursor in the position after the double character before the space
- I quickly start pressing one digit for example "3" the resulting characters are 33 33 33
- sometimes it is inserted well by the replacement method and sometimes new characters are inserted, this should not be.

**Comment by Keidan** [comment]
I suspect that the keyboard's auto-suggestion is responsible for this addition of characters (this is what I observe at home and sometimes it replaces the characters without my asking).
So I'll disable it in this view and we'll see in use.
For now, this seems to solve the problem
