### ISSUE TITLE
ability to edit multiple files at the same time

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#92]
sometimes I need to transfer parts of data from one file to another file. this is convenient if you can open two files at the same time. but now you can only edit one file at a time.
is it possible to make it possible to open two files at the same time and edit them?

**Comment by Keidan** [comment]
I'll try to analyze the feasibility of this request, but I don't hide from you that it is not guaranteed that I will arrive at a satisfactory result, and even less possible...
I've several difficulties:
- The development time of this feature.
- The memory consumption according to the opened files.
- The contexts of the views, and depending on the Android components I'll have to use, it might be too complicated (Android tends to purge unused views for a while). 
- etc...

**Comment by Keidan** [comment]
I'll not implement this feature.
 I'd a lot of research and came to the following conclusions:
- Apart from cheating with views, I can't use Android components (like fragments) which all have a lifecycle (this is a real problem for my use).
- To present the file selection as I would like, I have to code everything manually.
- I'm not going to have enough time between my family life, my work, my projects, solving the issues of this project and developing this feature.
