### ISSUE TITLE
the app is crashing

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#96]
1. updated the app 
2. opening the application
3. click on recently open
4. the app is crashing

I think the problem is checking the permission for files after updating the application

[log.zip](https://github.com/Keidan/HexViewer/files/6984351/log.zip)

**Comment by Keidan** [comment]
what version of android are you using?

**Comment by OmlineEditor** [comment]
android 9.0

**Comment by Keidan** [comment]
it's weird because I haven't touched this part for a while... and normally for all Android versions >= 6 and < 11 I don't really use the permissions imposed by Android 11.

Do you have it all the time? or is it a file you had open a while ago?

**Comment by Keidan** [comment]
I need more information

- Is the problem systematic?
- What is the latest version of HewViewer used with this file?
- Which file manager was used to open the file?

**Comment by OmlineEditor** [comment]
1) Is the problem systematic? - no, if you clear all the application data without reinstalling, the problem disappears. also, the problem disappears if you open all the files from the history using the open via menu method. then all the problems disappear

2) What is the latest version of HewViewer used with this file? - I don't remember exactly maybe 1.15

3) Which file manager was used to open the file? - built into the system. I don't know the exact version and name of the manager, it doesn't have a menu about the program

**Comment by Keidan** [comment]
I will at least avoid the crash .... permissions issues on Android give me a headache ...

**Comment by OmlineEditor** [comment]
if there are problems with the files just talk about it without crashing the application https://github.com/Keidan/HexViewer/issues/104
