### ISSUE TITLE
moving everything

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#98]
for the convenience of working in landscape mode, you need to make a slider that will move everything that is on the screen. it is not possible to edit the text without a slider. we discussed this and you will make a slider, but it seems that you have forgotten.
![slider](https://user-images.githubusercontent.com/13348933/129401689-7ea042a9-2f38-4981-b57c-d14c3e06c2b2.jpg)

**Comment by Keidan** [comment]
I can't really add this scrollable area... the two ListView components (and I won't do without) that are in the view react badly when they are in a scrollable view.

I'll try to see if I can propose an alternative by making the source and result sections expandable... 


Your use case just doesn't make sense, your keyboard itself is almost the size of the screen ^^.

**Comment by Keidan** [comment]
![IMG_20210814_172503](https://user-images.githubusercontent.com/3134348/129451289-6ea7a307-395c-40c6-8949-81c12b11fbaa.jpg)
This is the best I can do... The behavior of android:
* If everything is displayed:
  * Source block occupies~25% of the display
  * The result block occupies ~25% of the display
  * The text block occupies ~50% of the display
* If the source or result block is not displayed:
  * The source or result block occupies ~50% of the display
  * The text block occupies~50% of the display.
* If the source block and the result are not displayed :
  * Labels occupies  ~2% of the display
  * The text block occupies ~98% of the display.

**Comment by OmlineEditor** [comment]
good idea
