### ISSUE TITLE
font size in edit mode

### ISSUE THREAD

**Issue by OmlineEditor** [Keidan/HexViewer#99]
now you can change the font size in the viewing mode, but you can not change the font in the editing mode, it is always constant. can you make settings to change the font size in edit mode?

more flexible settings for editing, people will be able to adjust the best font size for their vision.

**Comment by Keidan** [comment]
I will only allow changing the font size for lists (as for the main view), but not the font size of all components in the line edit view.
I do not intend to bypass the system accessibility features.
Another point I don't want to change the number of digits to display, today it is hardcoded to 8 and it will stay at 8.

**Comment by OmlineEditor** [comment]
ok. make at least a little more flexible interface

**Comment by Keidan** [comment]
@OmlineEditor 
In the settings (settings->lanscape or portrait) I added the following section:
Line editing view -> Вид редактирования линий

The above translation corresponds to the title of the section (at the same level as the other titles (those in blue).
Is it right for you?

**Comment by OmlineEditor** [comment]
maybe it's better to replace specify: **_text in edit mode_** ?
in Russian, the text most clearly sounds like this: **_Текст в режиме редактирования_**

now there are more options, there is a view mode and there is an edit mode.
I think it will be necessary to change the words in the settings. 

Text in hexadecimal (without line numbers)  -> **_View_** text in hexadecimal (without line numbers)
Text in hexadecimal (with line numbers) -> **_View_** text in hexadecimal (with line numbers)
Plain text -> **_View_** plain text
Line editing view -> Text in edit mode
etc...

you need to make more understandable names for people who launched the program for the first time and do not understand the meaning of the menu.

what do you think about this?

**Comment by Keidan** [comment]
Ok ok, but what are the Russian translations?

**Comment by OmlineEditor** [comment]
View text in hexadecimal (with line numbers) => Просмотр текста в hex (с номерами строк)
View text in hexadecimal (without line numbers)  => Просмотр текста в hex (без номеров строк)
View plain text   => Просмотр простого текста
text in edit mode   =>  Текст в режиме редактирования

**Comment by Keidan** [comment]
thanks :)
